### ISSUE TITLE
Difference with merging objects directly?

### ISSUE THREAD

**Issue by tomsdev** [joe-bell/stitches-mixins#5]
Hi, I'm sure there are some stitches specific benefits in reusing the styles with your approach but I can't find what benefits they are exactly. Would be great if you could explain it and maybe add to the readme?

E.g. to mix styles in JS I would usually export an object with the styles and then use the ... operator to merge it in my component style. I forked your codesandbox example and modified your shadow mixing to use my approach instead so you can check it works too: https://codesandbox.io/s/stitches-mixins-demo-forked-mm64c?from-embed=&file=/src/stitches.config.ts

**Comment by tomsdev** [comment]
cc @joe-bell

**Comment by joe-bell** [comment]
Hey @tomsdev! My understanding is that there isn't much/any difference here from a technical perspective. The `stitches-mixins` approach is more about the Dev Experience; it's all about having a single source of truth for your design

You could absolutely import things manually if you prefer, but `stitches-mixins` aims to keep things driven by `stitches.config.js`

I hope that answers your question?

**Comment by tomsdev** [comment]
Oh ok that's a little disappointing, I was hoping there were more benefits. Are you sure there aren't?

Having a single source of truth is still possible in my example. If I export the mixin from the stitches file and wrap it in a single export "mixin" object (I updated the codesandbox to do that instead).
https://codesandbox.io/s/stitches-mixins-demo-forked-mm64c?from-embed=&file=/src/stitches.config.ts

Moreover, currently when using TypeScript the DX seems better in my example because I can get autocompletion, compiler checks for typos, can compose mixins objects, or even refactor a mixin to take a parameter if needed.

**Comment by tomsdev** [comment]
cc @peduarte @jonathantneal, maybe they can see some other benefits here?

**Comment by joe-bell** [comment]
It's worth noting that Stitches is still in `beta` and they are looking into options for "`util` type helpers" etc. Once these types are in, autocompletion shouldn't be such an issue

You're absolutely free to do what suits your preference - that's the beauty of Stitches!

**Comment by joe-bell** [comment]
Going to close this as I'm not too sure what's expected here–let's allow some breathing room for Stitches beta and revisit
